<?php

/**
 * EventlogController.php
 *
 * -Description-
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @link       https://www.librenms.org
 *
 * @copyright  2018 Tony Murray
 * @author     Tony Murray <murraytony@gmail.com>
 */

namespace App\Http\Controllers\Table;

use App\Facades\LibrenmsConfig;
use App\Models\Eventlog;
use Carbon\Carbon;
use Illuminate\Support\Facades\Blade;
use LibreNMS\Enum\Severity;
use LibreNMS\Util\Url;

class EventlogController extends TableController
{
    protected $model = Eventlog::class;

    public function rules()
    {
        return [
            'device' => 'nullable|int',
            'device_group' => 'nullable|int',
            'eventtype' => 'nullable|string',
            'start_date' => 'nullable|date_format:Y-m-d',
            'end_date' => 'nullable|date_format:Y-m-d',
        ];
    }

    public function searchFields($request)
    {
        return ['message'];
    }

    protected function filterFields($request)
    {
        return [
            'device_id' => 'device',
            'type' => 'eventtype',
        ];
    }

    protected function sortFields($request)
    {
        return ['datetime', 'type', 'device_id', 'message', 'username'];
    }

    /**
     * Defines the base query for this resource
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder
     */
    public function baseQuery($request)
    {
        return Eventlog::hasAccess($request->user())
            ->with('device')
            ->when($request->device_group, function ($query) use ($request) {
                $query->inDeviceGroup($request->device_group);
            })
            ->when($request->start_date, function ($query) use ($request) {
                $query->where('datetime', '>=', $request->start_date . ' 00:00:00');
            })
            ->when($request->end_date, function ($query) use ($request) {
                $query->where('datetime', '<=', $request->end_date . ' 23:59:59');
            });
    }

    protected function getExportHeaders()
    {
        return [
            'Timestamp',
            'Type',
            'Device',
            'Message',
            'User',
        ];
    }

    protected function formatExportRow($eventlog)
    {
        return [
            (new Carbon($eventlog->datetime))->setTimezone(session('preferences.timezone') ?? config('app.timezone'))->format(LibrenmsConfig::get('dateformat.compact')),
            $eventlog->type,
            $eventlog->device ? $eventlog->device->displayName() : 'unknown',
            $eventlog->message,
            $eventlog->username ?: 'System',
        ];
    }

    /**
     * @param  Eventlog  $eventlog
     */
    public function formatItem($eventlog)
    {
        return [
            'datetime' => $this->formatDatetime($eventlog),
            'device_id' => Blade::render('<x-device-link :device="$device"/>', ['device' => $eventlog->device]),
            'type' => $this->formatType($eventlog),
            'message' => $this->formatMessage($eventlog),
            'username' => $eventlog->username ?: 'System',
        ];
    }

    private function formatMessage($eventlog)
    {
        $msg = htmlspecialchars($eventlog->message);

        // Highlight ONLY traps generated by NMS SNMP Forwarding for Alert Rules
        if (str_contains($eventlog->message, '58158.9.188')) {
            // Check if state is RECOVERED ("58158.9.188.2":"0", "58158.9.188.3":"RECOVERED", "58158.9.188.5":"Clear")
            if (
                str_contains($eventlog->message, '"RECOVERED"') ||
                str_contains($eventlog->message, '"Clear"') ||
                str_contains($eventlog->message, '58158.9.188.2":"0"') ||
                str_contains($eventlog->message, '58158.9.188.3":"0"')
            ) {
                return '<span style="color: #2ecc71; font-weight: bold;">[RECOVERED] </span>' . $msg;
            }
            return '<span style="color: #e74c3c; font-weight: bold;">[ACTIVE] </span><span style="color: #e74c3c; font-weight: bold;">' . $msg . '</span>';
        }

        // All other event log messages remain plain/white as before
        return $msg;
    }

    private function formatType($eventlog)
    {
        if ($eventlog->type == 'interface') {
            if (is_numeric($eventlog->reference)) {
                $port = $eventlog->related;
                if (isset($port)) {
                    return Blade::render('<b><x-port-link :port="$port">{{ $port->getShortLabel() }}</x-port-link></b>', ['port' => $port]);
                }
            }
        } elseif ($eventlog->type == 'stp') {
            return Blade::render('<x-device-link :device="$device" tab="stp">stp</x-device-link>', ['device' => $eventlog->device]);
        } elseif (in_array($eventlog->type, \LibreNMS\Enum\Sensor::values())) {
            if (is_numeric($eventlog->reference)) {
                $sensor = $eventlog->related;
                if (isset($sensor)) {
                    return '<b>' . Url::sensorLink($sensor, $sensor->sensor_descr) . '</b>';
                }
            }
        }

        return htmlspecialchars($eventlog->type);
    }

    private function formatDatetime($eventlog)
    {
        $output = "<span class='alert-status ";
        $output .= $this->severityLabel($eventlog->severity);
        $output .= " eventlog-status'></span>";
        $output .= (new Carbon($eventlog->datetime))->setTimezone(session('preferences.timezone')?? config('app.timezone'))->format(LibrenmsConfig::get('dateformat.compact'));

        return $output;
    }

    /**
     * @param  Severity  $eventlog_severity
     * @return string $eventlog_severity_icon
     */
    private function severityLabel($eventlog_severity)
    {
        return match ($eventlog_severity) {
            Severity::Ok => 'label-success',
            Severity::Info => 'label-info',
            Severity::Notice => 'label-primary',
            Severity::Warning => 'label-warning',
            Severity::Error => 'label-danger',
            default => 'label-default', // Unknown
        };
    }

    public function forward(\Illuminate\Http\Request $request)
    {
        $request->validate([
            'syslog_ip' => 'required|string',
            'syslog_port' => 'required|integer|between:1,65535',
        ]);

        $rawInput = $request->input('syslog_ip');
        $port = (int) $request->input('syslog_port');

        $ipList = array_filter(array_map('trim', preg_split('/[\s,]+/', $rawInput)));
        if (empty($ipList)) {
            return response()->json(['success' => false, 'message' => 'Please enter at least one valid IP address or hostname.'], 422);
        }

        $validatedHosts = [];
        foreach ($ipList as $ip) {
            if (! filter_var($ip, FILTER_VALIDATE_IP)) {
                if (! preg_match('/^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$/i', $ip) && ! preg_match('/^[a-z0-9]+(-[a-z0-9]+)*$/i', $ip)) {
                    return response()->json(['success' => false, 'message' => "Invalid IP address or hostname format: {$ip}"], 422);
                }
                $resolved_ip = gethostbyname($ip);
                if ($resolved_ip === $ip) {
                    return response()->json(['success' => false, 'message' => "Hostname '{$ip}' does not resolve to an IP."], 422);
                }
            }
            $validatedHosts[] = $ip;
        }

        $finalHostStr = implode(', ', $validatedHosts);

        // Persist settings to database config table
        LibrenmsConfig::persist('eventlog_forward_syslog_host', $finalHostStr);
        LibrenmsConfig::persist('eventlog_forward_syslog_port', $port);

        return response()->json([
            'success' => true,
            'message' => 'Syslog server configuration saved successfully (' . count($validatedHosts) . ' host(s)).',
        ]);
    }

    public function testForward(\Illuminate\Http\Request $request)
    {
        $request->validate([
            'syslog_ip' => 'required|string',
            'syslog_port' => 'required|integer|between:1,65535',
        ]);

        $rawInput = $request->input('syslog_ip');
        $port = (int) $request->input('syslog_port');

        $ipList = array_filter(array_map('trim', preg_split('/[\s,]+/', $rawInput)));
        if (empty($ipList)) {
            return response()->json(['success' => false, 'message' => 'Please enter at least one valid IP address or hostname.'], 422);
        }

        $sentCount = 0;
        $failedHosts = [];

        $priority = 24 + 6; // facility: daemon (3), severity: info (6) => 3 * 8 + 6 = 30
        $timestamp = Carbon::now()->format('M d H:i:s');
        $syslog_msg = "<{$priority}>{$timestamp} localhost telequill_eventlog[test]: This is a test syslog message from Telequill.";

        foreach ($ipList as $ipHost) {
            $targetIp = $ipHost;
            if (! filter_var($targetIp, FILTER_VALIDATE_IP)) {
                if (! preg_match('/^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$/i', $targetIp) && ! preg_match('/^[a-z0-9]+(-[a-z0-9]+)*$/i', $targetIp)) {
                    $failedHosts[] = "$ipHost (invalid format)";
                    continue;
                }
                $resolved_ip = gethostbyname($targetIp);
                if ($resolved_ip === $targetIp) {
                    $failedHosts[] = "$ipHost (unresolved)";
                    continue;
                }
                $targetIp = $resolved_ip;
            }

            if (($socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP)) === false) {
                $failedHosts[] = "$ipHost (socket creation failed)";
                continue;
            }

            if (socket_sendto($socket, $syslog_msg, strlen($syslog_msg), 0, $targetIp, $port) === false) {
                $failedHosts[] = "$ipHost (send failed)";
            } else {
                $sentCount++;
            }
            socket_close($socket);
        }

        if ($sentCount > 0 && empty($failedHosts)) {
            return response()->json([
                'success' => true,
                'message' => "Test syslog packet sent successfully to {$sentCount} target server(s).",
            ]);
        } elseif ($sentCount > 0) {
            return response()->json([
                'success' => true,
                'message' => "Sent test syslog packet to {$sentCount} host(s), but failed for: " . implode(', ', $failedHosts),
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'Failed to send test syslog packets. Errors: ' . implode(', ', $failedHosts),
        ], 500);
    }

    public function forwardSnmpTrap(\Illuminate\Http\Request $request)
    {
        $request->validate([
            'snmptrap_ip' => 'required|string',
            'snmptrap_port' => 'required|integer|between:1,65535',
        ]);

        $rawInput = $request->input('snmptrap_ip');
        $port = (int) $request->input('snmptrap_port');

        $ipList = array_filter(array_map('trim', preg_split('/[\s,]+/', $rawInput)));
        if (empty($ipList)) {
            return response()->json(['success' => false, 'message' => 'Please enter at least one valid IP address or hostname.'], 422);
        }

        $validatedHosts = [];
        foreach ($ipList as $ip) {
            if (! filter_var($ip, FILTER_VALIDATE_IP)) {
                if (! preg_match('/^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$/i', $ip) && ! preg_match('/^[a-z0-9]+(-[a-z0-9]+)*$/i', $ip)) {
                    return response()->json(['success' => false, 'message' => "Invalid IP address or hostname format: {$ip}"], 422);
                }
                $resolved_ip = gethostbyname($ip);
                if ($resolved_ip === $ip) {
                    return response()->json(['success' => false, 'message' => "Hostname '{$ip}' does not resolve to an IP."], 422);
                }
            }
            $validatedHosts[] = $ip;
        }

        $finalHostStr = implode(', ', $validatedHosts);

        // Persist settings to database config table
        LibrenmsConfig::persist('snmptrap_forward_host', $finalHostStr);
        LibrenmsConfig::persist('snmptrap_forward_port', $port);

        return response()->json([
            'success' => true,
            'message' => 'SNMP Trap server configuration saved successfully (' . count($validatedHosts) . ' host(s)).',
        ]);
    }

    public function testForwardSnmpTrap(\Illuminate\Http\Request $request)
    {
        $request->validate([
            'snmptrap_ip' => 'required|string',
            'snmptrap_port' => 'required|integer|between:1,65535',
        ]);

        $rawInput = $request->input('snmptrap_ip');
        $port = (int) $request->input('snmptrap_port');

        $ipList = array_filter(array_map('trim', preg_split('/[\s,]+/', $rawInput)));
        if (empty($ipList)) {
            return response()->json(['success' => false, 'message' => 'Please enter at least one valid IP address or hostname.'], 422);
        }

        $sentCount = 0;
        $failedHosts = [];

        foreach ($ipList as $ipHost) {
            $targetIp = $ipHost;
            if (! filter_var($targetIp, FILTER_VALIDATE_IP)) {
                if (! preg_match('/^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$/i', $targetIp) && ! preg_match('/^[a-z0-9]+(-[a-z0-9]+)*$/i', $targetIp)) {
                    $failedHosts[] = "$ipHost (invalid format)";
                    continue;
                }
                $resolved_ip = gethostbyname($targetIp);
                if ($resolved_ip === $targetIp) {
                    $failedHosts[] = "$ipHost (unresolved)";
                    continue;
                }
                $targetIp = $resolved_ip;
            }

            $cmd = sprintf(
                '/usr/bin/snmptrap -v 2c -c %s udp:%s:%d 0 %s %s s %s %s s %s %s s %s %s s %s %s s %s %s s %s %s s %s 2>&1',
                escapeshellarg('public'),
                escapeshellarg($targetIp),
                $port,
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.6.1.0.6'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.1'), escapeshellarg('127.0.0.1'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.2'), escapeshellarg('LibreNMS-Server'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.3'), escapeshellarg('ACTIVE'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.4'), escapeshellarg('Equipment'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.5'), escapeshellarg('Info'),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.6'), escapeshellarg(date('Y M j H:i:s ')),
                escapeshellarg('SNMPv2-SMI::enterprises.58158.9.188.7'), escapeshellarg('Test SNMP Trap Connection')
            );
            $output = [];
            $retval = 0;
            exec($cmd, $output, $retval);

            if ($retval === 0) {
                $sentCount++;
            } else {
                if (($socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP)) !== false) {
                    $test_trap = "localhost\nUDP: [127.0.0.1]:54321->[127.0.0.1]:162\nDISMAN-EVENT-MIB::sysUpTimeInstance 1:0:00:00.00\nSNMPv2-MIB::snmpTrapOID.0 SNMPv2-SMI::enterprises.9.9.41.2.0.1\n";
                    if (socket_sendto($socket, $test_trap, strlen($test_trap), 0, $targetIp, $port) !== false) {
                        $sentCount++;
                    } else {
                        $failedHosts[] = "$ipHost (send failed)";
                    }
                    socket_close($socket);
                } else {
                    $failedHosts[] = "$ipHost (send failed)";
                }
            }
        }

        if ($sentCount > 0 && empty($failedHosts)) {
            return response()->json([
                'success' => true,
                'message' => "Test SNMP trap packet sent successfully to {$sentCount} target server(s).",
            ]);
        } elseif ($sentCount > 0) {
            return response()->json([
                'success' => true,
                'message' => "Sent test SNMP trap to {$sentCount} host(s), but failed for: " . implode(', ', $failedHosts),
            ]);
        }

        return response()->json([
            'success' => false,
            'message' => 'Failed to send test SNMP trap packets. Errors: ' . implode(', ', $failedHosts),
        ], 500);
    }
}
